version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-130yycyirn3nq"
s3_prefix = "lambda-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
