AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - my.sample.service::springboot-sample
Resources:
  SpringbootSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my.sample.service.StreamLambdaHandler::handleRequest
      Runtime: java11
     # CodeUri: target/springboot-sample-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringbootSampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringbootSampleApi
